pipeline {
    agent any

    tools {
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Compile') {
            steps {
                dir('Mega-Project-CI-main') {
                    sh "mvn clean compile"
                }
            }
        }

        stage('Testing') {
            steps {
                dir('Mega-Project-CI-main') {
                    sh "mvn test"
                }
            }
        }

        stage('Package Application') {
            steps {
                dir('Mega-Project-CI-main') {
                    // Создаем тот самый .jar файл
                    sh "mvn package -DskipTests" 
                }
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('Mega-Project-CI-main') {
                    withSonarQubeEnv('sonar') {
                        sh """
                            $SCANNER_HOME/bin/sonar-scanner \
                            -Dsonar.projectKey=gcbank \
                            -Dsonar.projectName=gcbank \
                            -Dsonar.java.binaries=target
                        """
                    }
                }
            }
        } 

        stage('Quality Gate Check') {
            steps {
                dir('Mega-Project-CI-main') {
                    timeout(time: 1, unit: 'HOURS') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }

        stage('Trivy FS Scan') {
            steps {
                dir('Mega-Project-CI-main') {
                    sh "trivy fs --format table -o fs-report.html ."
                }
            }
        }

        stage('Build & Push Docker') {
            steps {
                dir('Mega-Project-CI-main') {
                    script {
                        // ПРОВЕРЬ: ID в Jenkins должен быть именно docker-cred
                        withDockerRegistry(credentialsId: 'docker-cred') {
                            sh "docker build -t 1ezgin/bankapp:v${BUILD_NUMBER} ."
                            sh "docker push 1ezgin/bankapp:v${BUILD_NUMBER}"
                        }
                    }
                }
            }
        } 

        stage('Publish to Nexus') { 
            steps { 
                dir('Mega-Project-CI-main') {
                    withMaven(globalMavenSettingsConfig: 'devops-amir', maven: 'maven3', traceability: true) {
                        sh "mvn deploy -DskipTests"
                    }
                }
            } 
        } 
    }
}
