pipeline {
    agent any

    tools {
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Compile') {
            steps {
                dir('Mega-Project-CI-main') {
                    sh "mvn clean compile"
                }
            }
        }

        stage('Testing') {
            steps {
                dir('Mega-Project-CI-main') {
                    sh "mvn test"
                }
            }
        }

        stage('Sonar Analysis') {
            steps {
                dir('Mega-Project-CI-main') {
                    withSonarQubeEnv('sonar') {
                        sh """
                            $SCANNER_HOME/bin/sonar-scanner \
                            -Dsonar.projectKey=gcbank \
                            -Dsonar.projectName=gcbank \
                            -Dsonar.java.binaries=target
                        """
                    }
                }
            }
        }
    }
}
