pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', 
                    credentialsId: '1ezgin', 
                    url: 'https://github.com/1ezgin/ultimate-full-devops-project.git'
            }
        }
        
        stage('Kubernetes Deployment') {
            steps {
                script {
                    withKubeConfig(
                        caCertificate: '', 
                        clusterName: 'amir-project-cluster', 
                        contextName: '', 
                        credentialsId: 'k8-token', 
                        namespace: 'webapps', 
                        restrictKubeConfigAccess: false, 
                        serverUrl: 'https://96D7D7E2408358362593950D9CF68C95.gr7.eu-central-1.eks.amazonaws.com'
                    ) {
                        dir('Mega-Project-CD-main/Manifest') {
                            sh "kubectl apply -f manifest.yaml -n webapps"
                            sh "kubectl apply -f HPA.yaml -n webapps"
                            
                            echo "Waiting for pods to pull new images..."
                            sleep 20
                            
                            sh "kubectl get pods -n webapps"
                            sh "kubectl get service -n webapps"
                        }
                    }
                }
            }
        }
    }
}
